### ISSUE TITLE
working on Fedora?

### ISSUE THREAD

**Issue by pwright** [redhataccess/pantheon-cmd#45]
got this error after installing on Fedora 34:

```
$ pcmd

Traceback (most recent call last):
  File "/usr/lib64/PantheonCMD/pcmd.py", line 14, in <module>
    from pcprvalidator import get_changed_files, get_all_modules, get_all_assemblies, get_undetermined_files, get_no_prefix_files
ModuleNotFoundError: No module named 'pcprvalidator'
$ pcmd -h
Traceback (most recent call last):
  File "/usr/lib64/PantheonCMD/pcmd.py", line 14, in <module>
    from pcprvalidator import get_changed_files, get_all_modules, get_all_assemblies, get_undetermined_files, get_no_prefix_files
ModuleNotFoundError: No module named 'pcprvalidator'
```
This could easily be my config, just wondering if folks have successfully built/installed on Fedora 34?

**Comment by adahms** [comment]
Hey @pwright - thanks for the issue!

Two dependencies were missing from the spec file. 

I've added these on branch Issue_45 and submitted a PR under https://github.com/redhataccess/pantheon-cmd/pull/47

Could you see if the build process on that branch works for you?
